credentials_path: "credentials.yaml"
browser_path: "C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe"
driver_path: "drivers/chromedriver.exe"
tex_template_path: "templates/paper_template.tex"
prompt_cfg_path: "templates/prompt_config.yaml"
review_cfg_path: "templates/review_config.yaml"
out_dir: "out"
out_structure_filename: "laststrucutre.yaml"
out_tex_filename: "lastpaper.tex"
out_dump_filename: "lastpaper.dump"
