subject: "Langmuir Monolayers and Langmuir-Blodgett Films"

gen_struct_prompt: |
  **Academic Structure Engineering Prompt**

  You are a {subject} research architect specializing in comprehensive literature taxonomies. Your task is to design a survey structure that optimally organizes knowledge from provided sources while exposing research gaps.

  **Core Requirements:**
  1. Structural Depth: 
    - 6-12 main sections with 3-5 subsections each
    - Progressive flow: Foundational → Methodological → Analytical → Forward-looking
    - Mandatory elements in every section:
      * Historical lineage (2+ key works)
      * Technical decomposition
      * Cross-study comparison
      * Challenge/critique subsection
      * Emerging directions

  2. Content Specifications:
    - Subsection descriptions must include:
      a) Key theories/concepts to analyze
      b) Required methodology comparisons
      c) Controversies/open debates
      d) Minimum 3 seminal works to address
      e) Temporal analysis (evolution over decade)

  3. Source Integration:
    - Map each subsection to specific reference clusters
    - Identify under-explored connections between works
    - Highlight sections requiring new reference synthesis

  **Output Format (Strict YAML, 2-space identation):**
  ```yaml
  - title: "FORMAL SECTION TITLE"
    description: |
      "### Contextual Purpose Statement (15-25 words) ###
      
      - Subsection Title [Time Period Focus] [Primary Methodology] 
        - Core analysis: [Specific theories/techniques]
        - Required comparison: [Approach A] vs [Approach B] 
        - Critical works: \cite{authorA2023}, \cite{authorB2018}, \cite{authorC2020}
        - Controversy: [Description of academic dispute]
      
      - Next Subsection Title [Perspective Type] 
        - Historical development: [Decade-span analysis]
        - Technical components: [List of key elements]
        - Implementation challenges: [Specific obstacles]
        - Future synthesis potential: [Unexplored combinations]"
  ```

  Write only in English.

response_format: |
  **Gather thorough inisights from the provided references and follow the given instructions in the end**


write_prompt: |
  **Critical Directives (Non-Negotiable):**
  1. Output 650-750 words using this structure:
    - Comparative tables/figures with original captions (minimum 1 visual)
    - Critical discussion of conflicting research findings
    - Future research directions subsection

  2. Citation Protocol:
    \begin{{enumerate}}
    \item For each factual claim: \cite{{<author><year>}} 
    \item Create bibliography entries BEFORE writing content
    \item Cross-validate all references against previous sections
    \item New citations require new .bib entries
    \end{{enumerate}}

  3. Depth Enforcement Mechanisms:
    - If under 600 words: Add methodology comparison table
    - If no equations: Include formalization of key concepts
    - If under 5 citations: Expand historical context analysis

  4. Writing Style:
    - Maintain a formal, scientific, and objective tone
    - Gather stylistic inspiration from the provided references

  **Execution Workflow:**
  Step 1: Generate bibliography for this section ONLY
  \begin{{filecontents*}}{{mybib.bib}}
  % 8-12 entries minimum
  @article{{smith2024, author={{...}}, title={{...}}, year={{2024}}}}
  \end{{filecontents*}}

  Step 2: Write content using these linguistic constraints:
  - No markdown - Strict LaTeX only
  - \subsection for each technical subtheme
  - Algorithm pseudocode where applicable
  - \begin{{figure}}...\end{{figure}} with \caption{{Cited from \cite{{authorYear}}}}
  - Double check for duplicate bibtex entries
  - Use the Tikz LaTeX package to create any relevant visual elements
  - DO NOT include any preamble or first page command like \begin, \title.
  - DO NOT use any other bibliography command except '\cite' outside of the mybib.bib block
  - DO NOT use *unnumbered* section/subsection commands (like \section*, \subsection*)

  Step 3: Quality Assurance Check
  - Word count verification: [Actual: X | Target: 650±100]
  - Citation density: ≥1 per paragraph
  - Visual element technical depth

  **You are an expert in academic writing, specially in the field of {subject}.**

  You are writing a very important scientific survey paper based on the provided papers, section by section. Your task is to write the current section:

  # Section Structure:
  - TITLE: {title}
  - DESCRIPTION {description}

