subject: "Langmuir Monolayers and Langmuir-Blodgett Films"


gen_struct_prompt: |
  Using only the provided sources, generate a detailed structure for a scientific survey paper on the subject **{subject}**. Please provide your response in English.

  1. **Goal**: Create a formal and comprehensive structure for a survey paper that organizes the subject logically and thoroughly, emphasizing clarity and coherence.  

  2. **Instructions**:  
    - Do **not** include sections such as **Abstract** or **References**; these will be added separately.  
    - Include core sections and any additional sections/subsections inspired by the provided sources and your analysis of the subject. Be sure to include required sections for survey papers such as "Introduction", "Conclusions", and related.
    - Each section and subsection must have a descriptive title and a detailed explanation of its purpose and scope.  

  3. **Output Format**:  
    - Provide the structure in YAML format for easy integration.  
    - Format each section as follows:  
      ```yaml
      - title: "Section Title"
        description: |
          - Subsection Title
            - Brief explanation of what this subsection will cover.
            - Additional details as necessary.
          - Another Subsection Title
            - Explanation.
            - More details.
      ```  

  4. **Additional Guidance**:  
    - Ensure the structure reflects the patterns and insights from the sources while adhering to formal survey paper conventions.  
    - Focus on clarity, logical flow, and comprehensiveness to aid understanding and readability.  
    - Group related topics logically and ensure that the structure supports a cohesive narrative of the subject.


response_format: |
  **Please provide your output in LaTeX format, using the following guidelines for structure and content:**

  # LaTeX Sectioning:

  - Use numbered sectioning commands (\section, \subsection, etc.).
  - DO NOT use unnumbered commands (e.g., \section*, \subsection*).
  - Exclude the LaTeX preamble (e.g., \documentclass, \usepackage, \begin{{document}} and \end{{document}}).
  
  # Figures and Tables:

  - Use the TikZ package to include any figures that you think are relevant.
  - Refer to figures and tables in the text using proper citations, such as (Fig. X, AUTHOR, YEAR) or (Tab. X, AUTHOR, YEAR), where X is the number of the figure/table.
  
  # Citations and References:

  - Use the biblatex package for all references and citations.
  - Cite references in the text using the \cite{{nickname}} command.
  - Provide a bibliography section at the end of your response enclosed within the following environment:
  ```
  \begin{{filecontents*}}{{mybib.bib}}
  (REFERENCES IN BIBLATEX FORMAT)
  \end{{filecontents*}}
  ```

  - Assign reference nicknames in the format authoryear (e.g., smith2024), and cite them with \cite{{authoryear}} (e.g. \cite{{smith2024}})
  - Include citations for all works explicitly referenced in the section and for works cited indirectly through other authors.
  - There's no need to include the field 'abstract' in biblatex format.
  - Don't use '\printbibliography' anywhere
  - Don't use any other bibliography command besides \cite. 


write_prompt: |
  # Content Requirements:
  - Write a complete section for a review paper on {subject} titled {title}.
  - Base the section on the papers provided, incorporating:
    - Direct insights from the authors.
    - Insights from works cited by these authors.
  - Where relevant, include visual or tabular elements and discuss them in the text.

  # Writing Style
  - Maintain a formal, scientific, and objective tone throughout.
  - Structure your response to ensure the section is comprehensive and logically organized.
  - Draw inspiration from the writing style and tone of the papers you are referencing.

  # Length Requirements
  - Ensure the section contains at least 500–700 words (~2 pages in length).
  - Focus on detailed analysis, explanations, and discussions to achieve this length.

  # Section Structure:
  - TITLE: {title}
  - DESCRIPTION: {description}

  # Additional Notes:
  - Use as many references as necessary to provide a robust and well-supported discussion.
  - Ensure all references and citations are properly formatted and complete.

  The final output should adhere to these guidelines, providing a self-contained LaTeX section that is ready for inclusion in a longer document.


prompt_input_variables:
  - "title"
  - "description"
  - "subject"

