subject: "Langmuir Monolayers and Langmuir-Blodgett Films"

reference_extract_prompt: |
  """
  {pdfcontent}
  """

  - The text above is from a scientific paper.
  - Read and focus your attention on the section "References"
  
  - For every reference entry, you must take the Title and Author
  - DO NOT SKIP ANY REFERENCE
  - **Output in THIS FORMAT STRICTLY (yaml format, each item is an item from a list):**
  """
  - title: "REFERENCE_TITLE"
    author: "REFERENCE_AUTHOR"
  """
  - Make sure every variable value (REFERENCE_TITLE and REFERENCE_AUTHOR) are enclosed in double-quotes
  - If there is no apparent reference entry, ignore and do nothing
  - Examples of common Reference formats (X: a number, LN: last name, FA: first name abbreviation):
    - "(X) Author1LN, Author1F.; Author2LN, Author2F; ... AuthorNLN, AuthorNF. Some multiple words title finished by a dot. The rest"
      => This becomes: "title: 'Some multiple words title finished by a dot', author: "Author1LN, Author1F.; Author2LN, Author2F; ... AuthorNLN, AuthorNF"


gen_struct_prompt: |
  You are an expert in academic writing, specially in the field of **{subject}**.

  1. **GOAL**: generate a detailed structure for a scientific survey paper on the subject "{subject}". Be formal, comprehensive and organize the subject logically and thoroughly.
  
  2. **INSTRUCTIONS**:
    - Do not include sections such as **Abstract** or **References**;
    - Include core (Introductions, conclusions,...) sections/subsections and any additional ones inspired by the provided sources and your analysis of the subject.
    - Do not include the number of the section along with its title (e.g. 1. introduction, 2. methods...)
  
  3. **OUTPUT FORMAT**:
    - Provide the structure in YAML format
    - Do it as follows:
      ```yaml
      - title: "Section Title"
        description: |
          - Subsection Title
            - Brief explanation of what this subsection will cover.
            - Additional details as necessary.
          - Another Subsection Title
            - Explanation.
            - More details.
      ``` 

    **Provide your answer in English only**.


write_prompt: |
  **ALL YOUR FOLLOWING OUTPUT MUST ADHERE TO:**

  **You must use only LaTeX format, using the following guidelines for structure and content:**
  - LaTeX Sectioning:
    - Use only numbered sectioning commands (\section, \subsection, etc.) (don't use unnumbered such as \section*).
    - Exclude the LaTeX preamble (e.g., \documentclass, \usepackage, \begin{{document}} and \end{{document}}).

  - Citations and References:
    - DO NOT focus on citing anywhere. Focus only in writing.
    - DO NOT use any kind of BibTex or bibliography-related commands (\printbibliography, \cite, \bibliography, etc)

  - Figures and Tables:
    - If the section is too short (less than 500 words), you must include at least one visual element:
      - Include Figures by either using the TikZ package to create your own, or citing Figures from other works (and pointing it out)
      - Include tables that are adequate for the explanation of a topic
    - Else, acquire insights from the content of the section and judge if a Figure would be beneficial:
      - If there is some visual topic to be explained, consider using TikZ package to create a visual explanation

  - **Write in English only**.

  - **You are an expert in academic writing, specially in the field of {subject}.**

  - Your task is to write a complete survey on {subject} based on the references that are given.

  - You are pragmatic, so you are writing it section by section, and now you must write the section titled "{title}".

  - From your experience, you know that you must incorporate direct insights from the authors, from works cited by these authors, and insights you gather yourself.

  - As an academic writer, **you must inspire yourself with as many references as possible**. Nevertheless, do not copy the references.

  - Remember to include visual or tabular elements where relevant, using your expertise in visual elements.

  - The more you adhere to this guidelines, the better your performance -- always increase your performance.

  - Most important: maintain a formal, scientific, and objective tone. **THE MORE YOU WRITE, THE BETTER. YOU SHOULD WRITE AT LEAST 500 WORDS IN A SECTIION**.

  - Here's what you know that must be included in the section "{title}":
  {description}


add_reference_prompt: |
  """
  {bibdatabase}
  """

  - The text above is a database of BibTex entries available

  - **You are an expert in academic writing, specially in the field of {subject}.**

  - You are writing survey paper on the subject. You have it written alread, and now you only need to include as many references as you can.

  - The text below is a section of the paper, in LaTeX. The title of the section is: {title}

  - Given the section, you must go through the bibdatabse and add the references to this section:
    - ONLY use the command "\cite{{nickname}}", where "nickname" is the article ID to reference using bibtex (in bibtex, the nickname is given by: "@article{{nickname, ...}}")
    - DO NOT use any BibTex or bibliography commands in general, except for "\cite"
    - DO NOT alter the content of the section, focus only in adding RELEVANT references
    - To judge a reference relevant, you must:
      - If there is an "abstract" key available in the entry, read that abstract to check for the relevance in the current section
      - Else, use the other keys to extract as much information from the entry as possible (title, journal, authors) and check if they must be added or not.
    
  - Your output should only contain the section with "\cite" commands inserted, and nothing more.

  - Add AT LEAST 10 references PER SECTION

  - Section "{title}" content:
  {content}
